Added Discount Entity
cosmyn91d/ShopOnline pull request #5
Opened 2022-02-21 12:26 UTC by cosmyn91d

2022-02-24 07:16 UTC, mihai-nurv requested changes

2022-02-24 07:16 UTC, mihai-nurv commented on src/Core/Shop.Core.DomainEntities/Discount.cs
> +﻿using System;
remove unnecessary usings

2022-02-24 07:16 UTC, mihai-nurv commented on src/Core/Shop.Core.DomainEntities/Discount.cs
> +{
remove the namespace {}

2022-02-25 06:39 UTC, closed without merging

2022-02-25 06:40 UTC, AlexandraSauchea commented
Included in another pull request